### ISSUE TITLE
Papercuts in handle_local_options's return parameter

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk-rs-core#1592]
The virtual method `handle_local_options` returns a `glib::ExitCode`, it is special cased so that the application exits when the return value is positive (e.g. ExitCode::FAILUE, ExitCode::SUCCESS) and continues to run when when negative. 

Returning `(-1).into()` is an option, but it is not very nice.

**Comment by sdroege** [comment]
@A6GibKm Want to provide a PR for this? Docs say this:

```
   * Returns: an exit code. If you have handled your options and want
   * to exit the process, return a non-negative option, 0 for success,
   * and a positive value for failure. To continue, return -1 to let
   * the default option processing continue.
```

Now this just needs to be wrapped into meaningful types. All negative values are the same (default processing), 0 is success but no default processing, all values > 0 are errors and returned like that

**Comment by A6GibKm** [comment]
What I dont follow is when it is actually a return code? I will test later if 0 is a return code. 

It could be an enum

```
LocalOptionsHandling {
    ExitCode(glib::ExitCode),  //  >= 0
    DefaultProcessing,  // -1
}
```

or something like that.

**Comment by pjungkamp** [comment]
@A6GibKm Can we mark this fixed now?

**Comment by sdroege** [comment]
I think so. If something is still missing, a more specific issue for that would be useful.
